# Generated by Django 2.1 on 2019-09-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.IntegerField(),
        ),
    ]
